---
title: "Lab 06 - Functions and iterations"
author: "Sean"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
diamonds <- diamonds
  filter(diamonds, x > 0)




```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table * y / 100)

diamonds %>%
  summarise(avg_table = mean(table_mm))






diamonds %>%
  group_by(clarity) %>%
  summarise(avg_table = mean(table_mm))






```

better the clarity, smaller the table lenth

```{r}
diamonds %>%
  summarise(across(depth:z, mean, .names = "avg_{.col}"))




```

## Exercise 3

```{r}
gmean <- function(x){
  if( any(is.logical(x)) ){
  warning("<ERROR MESSAGE>")
  return(NaN)
}
  if( any(is.character(x)) ){
  warning("<ERROR MESSAGE>")
  return(NaN)
}
  if( any(x <= 0) ){
  warning("<ERROR MESSAGE>")
  return(NaN)
}
  exp(mean(log(x)))
}



```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


map(test_data, gmean)


```


## Exercise 5

```{r}
gmean <- function(x){
  if( any(is.logical(x)) ){
  warning("<ERROR MESSAGE>")
  return(NaN)
}
  if( any(is.character(x)) ){
  warning("<ERROR MESSAGE>")
  return(NaN)
}
  if( any(x <= 0) ){
  warning("<ERROR MESSAGE>")
  return(NaN)
}
  exp(mean(log(x)))
}




output <- vector(double, length(test_data))
for(i in seq_along(test_data)){
  test[[i]] <- gmean(test_data[[i]])
}





```

## Exercise 6

```{r}
map(test_data, gmean)

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```

## Exercise 10 (optional)

_Do derivation on paper, unless you know how to write LaTeX code_
